### ISSUE TITLE
New formats and community roles

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/meetups#6]
So from our discussion yesterday, I've come up with a few new ideas we could incorporate to our format. 

### Live Coding Meetups : 
In this format, the mentors of the community will build a small project while the regular members watch and ask questions. This way we can create an engaging environment in which our members can experience the development process of building something from scratch. The spontaneous nature of this format makes sure that the mentors make mistakes and feel clueless constantly. This lets the audience witness how someone with more experience figures out a solution. This format has the liberty of diverting as much from the topic as required to truly explain something. 

### Micro-conference Meetups : 
I tried to expand on the suggestions of Ramana as well as Nishant that we should let members teach small topics for like 10 mins. What I have in mind is, we can do dedicated meetups where our members can teach whatever programming concept they recently learned (under web development) to other members. It wouldn't include basic syntax teaching to beginners, as we'll cover that in separate teaching meetups. It is well known that teaching is the final step of learning something. By providing the platform for all our members to teach what they just learned, we can ensure that their understanding of the topic becomes more concrete. I like to think of this as mico-conference sessions  that span two - three hours. Each member speaking can take from 5 mins - 30 mins. We can confirm who is going to speak on what a week or two in advance and publish it on our event page. 

## Community Roles
I feel like we should have an intermediate role between being a mentor and a regular member. I'm thinking of a "volunteer" role. Members with this role can help with organizational tasks, community management and engagement, maybe even teaching the beginners. We could create a new WhatsApp group and Discord room for them as well.

<hr>

So what do you guys think? If you agree with all points, respond with a thumbs up. If you have any criticism, suggestions or thoughts to share, post them below and we can discuss.

**Comment by vramana** [comment]
* **Live Coding Meetups**: We can try this but the problem comes down to choosing the projects themselves. If you guys have some example project topics, please list them. 

* **Micro-conference meetups**: It doesn't feel correct the thing to do right now. We can revisit this after 2 months when we have more active members. For now, let's try if doing one 10 mins talk for a few (atleast 6) meetups and then later decide how to scale. If we see enough enthusiasm and people who want to talk, then we can think about this format. 

* **Community Roles**:  Usually :-1: for anything that increases structure.  I don't think it has any benefits right now. But if others think, benefits outwiegh the costs, we can go ahead.

**Comment by duttakapil** [comment]
@vramana we should definitely do one experiment meetup for each new format. I guess we could wait another month before trying the micro-conference meetup. 

We have other things to focus on till then. For example, community engagement. The volunteer role I feel will help a lot in this. They can post one development related link (news/video or whatever) in the group that might trigger a discussion. I feel this is a priority for us right now. We need to make people feel more comfortable in communicating in the group.

**Comment by vramana** [comment]
> For now, let's try if doing one 10 mins talk for a few (atleast 6) meetups and then later decide how to scale.

@duttakapil You didn't comment on this. Are you okay with this or not?

**Comment by duttakapil** [comment]
@vramana seems unnecessary to do right now. We should focus on the other three formats of meetups for the next month at least and then experiment with the micro-conference type meetups.

**Comment by vramana** [comment]
* The hate this name "micro-conference meetups" for some reason.
* If you directly plan to attempt directly have such meetup, there is very high possiblity it can fail really really hard. So, big :-1: from my side. 
* Even if it is unnecessary, just taking away 10 mins from the meetup will not affect the meetup itself. It's not we have to prepare something. All we have to do is ask one of the attending members to present a short topic.

**Comment by duttakapil** [comment]
- Okay. 
- I'm suggesting we think about **experimenting** with this a month or two later. It's a really good idea, and we should definitely wait till we have more active members willing to participate. 
- Never said it would. I'm just not focused on teaching beginners right now. Our active members are already familiar with the basics of JavaScript and I'm focused on providing value to them. Meaning, more practice sessions and live coding meetups. I think only that should be the focus for the next one month. Let's come back to this two weeks later?

**Comment by vramana** [comment]
One doesn't have to explain extreme basics, as we discussed in the WhatsApp group. They can talk about a ton of other things. For example closures, CSS Animations, selected features in ES2015 like arrow functions, for-of loops, const-let, etc., i.e,  things that don't take a whole lot of time to explain. We can tell them what to prepare for and even help in their preparation. 

We can start it whenever you and others feel like. The objective here is to make people comfortable speaking technical stuff incrementally.

**Comment by duttakapil** [comment]
@vramana good idea. We should definitely get back to this two or three weeks later

**Comment by khaledMohammed000** [comment]
1 .A big no to increasing the complexity of community roles , Instead we can have people just answer specific topics , **_Like i answer only Git-Github questions(Since that is my Forte for now)_**, like that we can all do one single job and then all of us collectively can make constructive discussions/debates ..
2. regarding live coding sessions : **_we should give our audience a set of topics and also few project ideas a week before the session_** then on **popular demand** we can do any from the list we give before hand
3.Micro-conference : we should have this thing every week for some time : **on what topics you might ask** : **_let people post topics they have problem understanding , then we can arrange them them in descending order of their frequency and assign it to people who know those topics best_**

**Comment by Pradhant** [comment]
Agreed Khaled. Let's not make this "WORK". It still should be a lot of fun and learning.

**Comment by duttakapil** [comment]
@khaledMohammed000 
1. Let's just put the volunteer role aside for sometime. We can come back to it later
2. We're already creating a list in #8. I don't see the point of asking members to vote on them. The mentors can finalize which one to do when. 
3. We have decided to put this format aside for a couple of weeks. Let's get back to this later?
