### ISSUE TITLE
Schedule for the next four meetups

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/Meetups#7]
Here's the schedule for the next four meetups : 

- 21st August (Sunday) : Pair Programming Meetup at Terminus Adda [Confirmed]

- 27th August (Saturday) : Live Coding Meetup at 91SB [Confirmed]

- 3rd September (Saturday) : Web Developer Meetup at 91SB [Confirmed]

- 11th September (Sunday) : Pair Programming Meetup [Planning - Location]

<hr>

The live coding and front-end pactice session are yet to be discussed and finalized. Let me know what you guys think of this schedule and if we are all on the same page

**Comment by vramana** [comment]
* Remove 21st from the list. There is nothing to plan about that. 

* Will it any better to state JavaScript Practice Session and Front-end Practice Session as simply Practice Sessions  or FCC Practice Session?? This way people are not tied up to any particular section they are solving in FCC. I don't see any reason why people who are doing Intermediate Projects should not JavaScript Practice Session.

**Comment by duttakapil** [comment]
@vramana 
- The point is not just to discuss but also to list down the schedule/plan for the next few meetups.
- We can call them Pair Programming Meetups until we reach a sufficient number of active members.

**Comment by vramana** [comment]
* If keeping that makes you happy, sure go with it. To me it just looks plain stupid. But whatever. 

> We can call them Pair Programming Meetups until we reach a sufficient number of active members.
*  Okay. So should we change the Title of this week event also to Pair Programming Meetup?

**Comment by duttakapil** [comment]
- I edited the details. Does it make more sense to you now? 
- We can do that, sure

**Comment by vramana** [comment]
I am against the idea of Live Coding Meetup on 27th. The whole thing feels rushed. I am feeling stressed without working anything. Last time it was really stressful when working on FlappyBird clone because we didn't have any idea whether we would complete or not. I was busy with work that week and @duttakapil was struggling to get the initial parts going. I had to temporarily set aside work and worked on the project to reach the deadline. I don't want to see that ever again.

 We have already discussed that we have to prepare a lot while doing these kinds of meetups. Let's first build projects. Once we are done with building a project. We can then put up a live coding meetup for that project.

**Comment by duttakapil** [comment]
@vramana I agree with your points to some extent. However, you also need to consider that :

- This live coding meetup does not exactly compare to the FlappyQuery meetup, because this is more spontaneous. The idea is to deliberately not prepare and try to figure it out on the fly, without any preparation. This would make the mentors susceptible to making mistakes and feeling lost. But it also allows us to resolve the problems on the fly, discussing possible solutions. All the while the members witnessing will get exposed to the authentic development process, if I may say.

- We'll have more than two mentors present to help out when we get stuck. This will make sure the second day scenario of the FlappyQuery meetup does not repeat. 

- We have the freedom to pick something much simpler for this particular meetup. Maybe even the GitHub API project we were thinking about for the REST API meetup last month.  

- We can also keep this closed to our community only, to make sure limited people attend. 

Also, suppose we remove this one from the schedule. What would we replace it with? Do you have any suggestions? A teaching meetup would require sufficient preparation again and we're already doing a practice meetup this weekend. Should we skip it, like last month?

**Comment by nishant-tomer** [comment]
For live coding event, I agree with kapil. I hope we start and get stuck. We can implement something simple... We can create a simple express app and can implement Oauth, OAuth2 . That's it ..all the social providers... What do you guys think?

**Comment by khaledMohammed000** [comment]
Guys I may be a bit off here from the topic but reading this entire discussion and also looking a the schedule . few points came to my mind
> 1. let us alternate between coding week and non-coding/less-coding/hang-out type week
            **_Reason : People spend entire week following curriculum online so it should be more fun during meetups_**
> 2. regarding 3 hours of Live coding .. A Big No . **_Reason : I attended classes where the instructor used >to code for 2 hours .... OMG those were really strenuous sessions_**

###Conclusion : 
> All the above stuff is good but reshuffle stuff to lessen strain on people following curriculum and shorten Stuff duration of Live coding

**Comment by vramana** [comment]
@nishant-tomer Nobody has any idea of node. People are getting wrecked in writing synchronous code. If we start saying async, callbacks wouldn't it be too much? I am very interested in this as future meetup. @duttakapil  and me have agreed that we will not touch on Backend until we grow a little. But now that you are here. Our options are little more open. I know that I am being a little conservative here but I don't know if that really the correct thing to do.

**Comment by nishant-tomer** [comment]
Oh. If it's about complexity of async, then ok.. we can do something in the browser...I really don't know if people will like node at the moment...or they will be distracted...for front end , we can try cloning some existing pen on codepen or front page of some company....but I have not much clue about css structures...and identifying modular abstractions in the design to group them into classes and so on and so forth.. I know the syntax and the concepts :).. I used to make block based abstractions...like whole page will be divided into rectangular blocks and each will have its class..and on and recursively ...:D

**Comment by vramana** [comment]
@khaledMohammed000 There is a big problem with your assumption. People are not spending the whole week on cirriculum. They are working in thier lives. I want our meetups to be place of retreat for those people to learn to something new and change thier careers. 

There may be many distractions at work or college or even home. So I want our meetups should provide an good enviroment where people can focus on learning and meet like-minded people to get some more inspiration. So, I argue that the meetups has to remain coding centered.  

I totally agree with the fact that it shouldn't be stressful. There may be many reasons why you felt strenous. But according to me time is the least factor. May be your teacher is bad. May be you weren't feeling interested in the topic. It is not sufficient evidence to conclude anything. May be you have not seen good live coding session. Time just flies by such live coding session. 

I don't think I am at that level. But to get to that level, I need to speak more so that I improve. Similar thing can be said for others.

There is big difference between classes and our meetups. For classes there is cumpulsion to attend but our meetups don't have that. That is a major point. Most of time people only come because they are interested. And you haven't even attend a single meetup yet. From my experience till now, it was never really stressful for anybody. Attend a few meetups and give your thoughts. If you are think we are doing something wrong, we will certainly change it.

**Comment by Pradhant** [comment]
Guys, I never was a part of anything close "Live" coding.  But I think it's too early, infact I'll make it more like a competition. Make teams and for that to happen, we need to know each other more. 

I would suggest for other meetings, can we do interactive sessions?
It's so much better to pair up experienced ones with the new ones and let them continue to work on projects. You guys can oversee what's happening with everyone.  i would suggest we do the below...
1. Start teams this weekend of next.
2. Ask them to pick projects themselves. Which involves everything from HTML to JS 
3. Work week on week and complete it in a month. During the course, there will be challenges and you guys can oversee the whole process and fix it. 
4. When you call sessions "practice sessions" it's pretty vague. It'll be a 100 times better if there's a "GOAL" for all sessions and it's continuous. 
5. What about new joinees every week, they join one of the teams either just observe this time or start contributing. Let the teams have their own offline conversations in the week, you guys will oversee everything on weekends or if there's a problem discuss on Discord. 

I hope I was clear. 
Cheers

**Comment by vramana** [comment]
@Pradhant A big :-1: to most suggestions. I don't think it will work at all. Everything will just simply crash and burn. But I am willing to reconsider my stance if you can bring me examples of where this type of culture succeeded. If you want my particular reasons, I can give them when we meet in person.

Practice Sessions are pretty well defined. The Goal is to achieve Front-End Certificated of FCC.May be we are not as explicit as we can be. We will be explict from now on.Thank you for pointing it out.

**Comment by Pradhant** [comment]
I don't have any experience in code but my expertise used to be in the area of training. Hence this was my observation as an outsider. There's more you can achieve when the sessions are team based with less talking from the facilitator. We just enable them and mentor through it and they continue working on it. So good luck with that!

Yes for practice sessions, if you meant the FCC curriculum then it makes sense.

**Comment by vramana** [comment]
This is not about experienced in coding. You have to understand that the community members have nothing at stake. So the setting you are imagining is pretty different from what will happen. Open communities work much differently from professional training sessions. It just is a lot of unnecessary maintenance work. Nobody has time to full time mentor teams of people. And we are not getting paid for any of our work. We have to be extemely careful of what work and how much work we choose. So, I tend usually make conservative choices.

From my experience, people work on and off on FCC. They don't work continuously because they have other things in their life. Take your case for example. You haven't made much progress till now. If a team has to progress. Everybody needs to give a good level of commitment. So these two different kind of behaviours don't go well together.

Show me meetup communities that work like this. I want to talk to such people.

**Comment by Pradhant** [comment]
You had to take my case for example huh ;)

**Comment by duttakapil** [comment]
@Pradhant I agree with your intention but I also agree with @vramana 's criticism. While your suggestion for creating teams sounds ideal, the reality will be very different for our community.  Just to create one effective team would take our maximum effort, simply because we don't have enough active members. And this also diverts from our original goal to help our members finish the FreeCodeCamp curriculum. We are already doing pair programming meetups where two members work together through the curriculum and we help them out whenever they get stuck. This format doesn't have any talking from the facilitator, as you say. 

Regarding the live coding meetups, it's just one format. And we decided on it based on our experience from the recent "jQuery Source Code" meetup. Right now we're just experimenting with these new formats. They are not concrete.   

How about this, why don't we put this suggestion aside till we reach sufficient active members and mentors? Until then, we can focus on our current structure. Sounds good?

**Comment by duttakapil** [comment]
@khaledMohammed000 I agree with you and @vramana on the point that meetups should be alternating in their stress levels. Which is why we keep switching between pair programming and teaching meetups right now. 

If you read the description for Live Coding meetups in #6 again, you'll find that they are structured to create an engaging environment, where members can ask questions and we have the liberty to divert from the topic to explain things properly. I hope this answers your concern

**Comment by khaledMohammed000** [comment]
@Pradhant look at it this way , by creating teams we are **creating dependency** , is it not ? where as we should be more **Decoupled** so that we can form a team on the go .. Just think this way .

**Comment by khaledMohammed000** [comment]
1. @vramana I put this

> regarding 3 hours of Live coding .. A Big No . Reason : I attended classes where the instructor used to code for 2 hours .... OMG those were really strenuous sessions

Because I had to pay just INR 500 for learning Design Patterns from a celebrated teacher , Things went crazy when the number of files/Packages even reached 3-5 
>Instructor tried to write the most simple code but things got escalated very quickly

**_#500 is like its almost free because i had 45-50 sessions @2hours everyday , Just like we buy something out of curiosity, this course was the same...I absolutely didn't have any Compulsion attending it , I did attended until 25 patterns and most funny thing was classes were during my Final Exams for 3-1_**


So am referring here what happens when things get complex , the flow of programs get insane to track , Plus **Pleople who are intending to learn Free Code Camps curriculum only on weekends/meetups**  They will struggle alot

2.**Regarding this am with you but am against duration of coding**

>So, I argue that the meetups has to remain coding centered.

3.**Ageed bro**

>And you haven't even attend a single meetup yet. From my experience till now, it was never really stressful for anybody. Attend a few meetups and give your thoughts. If you are think we are doing something wrong, we will certainly change it.

**Comment by vramana** [comment]
@khaledMohammed000 You made your point. Let's discuss the issue after you attend a few meetups.
